server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: backend-user-service
  datasource:
    url: ${POSTGRES_URL}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: us-east-1
    stack:
      auto: false
    s3:
      bucket: ${S3_BUCKET}
    endpoint: ${S3_URL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
  instance:
    prefer-ip-address: true

keycloak:
  auth-server-url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_MASTER_REALM}
  client-id: ${KEYCLOAK_MASTER_CLIENT_ID}
  username: ${KEYCLOAK_MASTER_USERNAME}
  password: ${KEYCLOAK_MASTER_PASSWORD}
  ssl-required: external
  public-client: false
  principal-attribute: preferred_username
  use-resource-role-mappings: true
  confidential-port: 0
